BottleName: "&6&lFrasco de XP &7(%value% XP)"
BottleEnchanter: "&dEngarrafado por&r %player%"
Value: "&dValor&r %value% XP"
AdminName: "&dEngarrafado por &rServer"
MinXp: 1
MaxXp: 1000000
DropPercentage: 100
Messages:
 NotEnough: "&cVocê só tem %pxp%!"
 Xpb:
  - "&6/satoshixp <quantidade>"
  - "&7Converte xp em frasco."
 XpTransferred: 
  - "&6Seu XP foi transferido para o frasco!"
  - "&c- %takenxp% XP"
 FullInventory: "&cSeu inventário está cheio, por favor libere algum espaço."
 MinXpMessage: "&cVocê tem que transformar no minimo %minxp% XP por frasco."
 MaxXpMessage: "&cVocê só pode colocar %maxxp% em um Frasco!"
 CantFind: "&cNão foi possivel encontrar %target%!"
 BottleRecive: "&6Jogador recebeu %xp%!"
 NoPermission: "&cVocê não tem permissão para usar esse comando!"
 NoNumber: "&cIsso não é um numero!"